:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= P2TSH End-to-End Tutorial

:numbered:

This tutorial is inspired from the link:https://learnmeabitcoin.com/technical/upgrades/taproot/#example-3-script-path-spend-signature[script-path-spend-signature] example of the _learnmeabitcoin_ tutorial.

It is customized to create, fund and spend from a P2TSH UTXO to a P2WPKH address.


== Pre-reqs

=== Bitcoin Core

The link:https://github.com/jbride/bitcoin/tree/p2tsh[p2tsh branch] of bitcoin core is needed.

Build instructions for the `p2tsh` branch are the same as `master` and is documented link:https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md[here].

As such, the following is an example series of steps (on a Fedora 42 host) to compile and run the `p2tsh` branch of bitcoin core:

. Set BITCOIN_SOURCE_DIR
+
-----
$ export BITCOIN_SOURCE_DIR=/path/to/root/dir/of/cloned/bitcoin/source
-----

. build
+
-----
$ cmake -B build \
        -DWITH_ZMQ=ON \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DBUILD_BENCH=ON \
        -DBUILD_DAEMON=ON \
        -DSANITIZERS=address,undefined

$ cmake --build build -j$(nproc)
-----

. run in either `regtest` or `signet` mode:

.. regtest:
+
-----
$ ./build/bin/bitcoind -daemon=0 -regtest=1 -txindex -prune=0
-----

.. signet:
+
-----
$ ./build/bin/bitcoind -daemon=0 -signet=1 -txindex -prune=0
-----
+
NOTE: If running in `signet`, your bitcoin core will need to be configured with the `signetchallenge` property.
link:https://edil.com.br/blog/creating-a-custom-bitcoin-signet[This tutorial] provides a nice overview of the topic.

=== Shell Environment

. *b-cli* command line alias:
+
Configure an alias to the `bitcoin-cli` command that connects to your customized bitcoin-core node.
+
ie: for signet
+
-----
$ alias b-cli=bitcoin-cli -conf=$HOME/configs/bitcoin.conf.signet
-----

. *jq*: ensure json parsing utility is installed and available via your $PATH.
. *awk* : standard utility for all Linux distros (often packaged as `gawk`).

=== Bitcoin Core Wallet

This tutorial assumes that a bitcoin core wallet is available.

. Set an environment variable specific to your Bitcoin network environment (regtest, signet, etc)
+
-----
$ export BITCOIN_NETWORK=regtest
-----

For example, the following would be sufficient:

-----

$ export W_NAME=anduro

$ b-cli -named createwallet \
    wallet_name=$W_NAME \ 
    descriptors=true \
    load_on_startup=true \
    blank=true

-----

== Fund P2TSH UTXO

. OPTIONAL: Indicate whether you prefer to use _Post Quantum Cryptography_ (in the form of _SLH-DSA_.  Default is the use of `Schnorr` signatures ).
+
-----
$ export USE_PQC=false
-----

. OPTIONAL: Define number of leaves in tap tree as well as the tap leaf to later use as the unlocking script:
+
-----
$ export TOTAL_LEAF_COUNT=5 \
    && export LEAF_OF_INTEREST=4
-----
+
NOTE: Defaults are 4 leaves with the first leaf (leaf 0 ) as the script to later use as the unlocking script. 

. Generate a P2TSH scripPubKey with multi-leaf taptree:
+
-----
$ export BITCOIN_ADDRESS_INFO=$( cargo run --example p2tsh_construction ) \
    && echo $BITCOIN_ADDRESS_INFO | jq -r .
-----
+
NOTE:  In `regtest`, you can expect a P2TSH address that starts with: `bcrt1z` .
+
NOTE: In the context of P2TSH, the _tree_root_hex_ from the response is in reference to the _quantum_root_ used in this tutorial.

. Set some env vars (for use in later steps in this tutorial) based on previous result:
+
-----
$ export QUANTUM_ROOT=$( echo $BITCOIN_ADDRESS_INFO | jq -r '.taptree_return.tree_root_hex' ) \
    && export LEAF_SCRIPT_PRIV_KEY_HEX=$( echo $BITCOIN_ADDRESS_INFO | jq -r '.taptree_return.leaf_script_priv_key_hex' ) \
    && export LEAF_SCRIPT_HEX=$( echo $BITCOIN_ADDRESS_INFO | jq -r '.taptree_return.leaf_script_hex' ) \
    && export CONTROL_BLOCK_HEX=$( echo $BITCOIN_ADDRESS_INFO | jq -r '.taptree_return.control_block_hex' ) \
    && export FUNDING_SCRIPT_PUBKEY=$( echo $BITCOIN_ADDRESS_INFO | jq -r '.utxo_return.script_pubkey_hex' ) \
    && export P2TSH_ADDR=$( echo $BITCOIN_ADDRESS_INFO | jq -r '.utxo_return.bech32m_address' )
-----

. View tapscript used in target leaf of taptree:
+
-----
$ b-cli decodescript $LEAF_SCRIPT_HEX | jq -r '.asm'
-----
+
NOTE:  If not using PQC, notice that this script commits to a Schnorr 32-byte x-only public key.
If using PQC, this script commits to a Schnorr 32-byte SLH-DSA pub key and a OP_SUCCESS127 (represented as `OP_SUBSTR`)


. fund this P2TSH address with the coinbase reward of a newly generated block:
+
Choose from one of the following networks:


.. Regtest
+
If on `regtest` network, then execute the following:
+
-----
$ export COINBASE_REWARD_TX_ID=$( b-cli -named generatetoaddress 1 $P2TSH_ADDR 5 | jq -r '.[]' ) \
    && echo $COINBASE_REWARD_TX_ID
-----
+
NOTE:  Sometimes Bitcoin Core may not hit a block (even on regtest).  If so, just try the above command again.

.. Signet
+
If on `signet` network, then execute the following:
+
-----
$ $BITCOIN_SOURCE_DIR/contrib/signet/miner --cli "bitcoin-cli -conf=$HOME/anduro-360/configs/bitcoin.conf.signet" generate \
    --address $P2TSH_ADDR \
    --grind-cmd "$BITCOIN_SOURCE_DIR/build/bin/bitcoin-util grind" \
    --min-nbits --set-block-time $(date +%s) \
    --poolid "MARA Pool"
-----

. view summary of all txs that have funded P2TSH address
+
-----
$ export P2TSH_DESC=$( b-cli getdescriptorinfo "addr($P2TSH_ADDR)" | jq -r '.descriptor' ) \
    && echo $P2TSH_DESC \
    && b-cli scantxoutset start '[{"desc": "'''$P2TSH_DESC'''"}]'
-----

. grab txid of first tx with unspent funds:
+
-----
$ export FUNDING_TX_ID=$( b-cli scantxoutset start '[{"desc": "'''$P2TSH_DESC'''"}]' | jq -r '.unspents[0].txid' ) \
    && echo $FUNDING_TX_ID
-----

. Set FUNDING_UTXO_INDEX env var (used later to correctly identify funding UTXO when generating the spending tx)
+
-----
$ export FUNDING_UTXO_INDEX=0
-----

. view details of funding UTXO to the P2TSH address:
+
-----
$ export FUNDING_UTXO=$( b-cli getrawtransaction $FUNDING_TX_ID 1 | jq -r '.vout['''$FUNDING_UTXO_INDEX''']' ) \
    && echo $FUNDING_UTXO | jq -r .
-----
+
NOTE:  the above only works when Bitcoin Core is started with the following arg:  -txindex

== Spend P2TSH UTXO


. Determine value (in sats) of funding utxo:
+
-----
$ export FUNDING_UTXO_AMOUNT_SATS=$(echo $FUNDING_UTXO | jq -r '.value' | awk '{printf "%.0f", $1 * 100000000}') \
    && echo $FUNDING_UTXO_AMOUNT_SATS
-----

. Generate additional blocks.
+
This is necessary if you have only previously generated less than 100 blocks.
+
Otherwise, you may see an error from bitcoin core such as the following when attempting to spend:
+
_bad-txns-premature-spend-of-coinbase, tried to spend coinbase at depth 1_

.. regtest
+
-----
$ b-cli -generate 110
-----

.. signet
+
This will involve having the signet miner generate about 110 blocks .... which can take about 10 minutes.
+
The `common/utils` directory of this project provides a script called: link:../../common/utils/signet_miner_loop.sh[signet_miner_loop.sh].


. Referencing the funding tx (via $FUNDING_TX_ID and $FUNDING_UTXO_INDEX), create the spending tx:
+
-----
$ export SPEND_DETAILS=$( cargo run --example p2tsh_spend )

$ export RAW_P2TSH_SPEND_TX=$( echo $SPEND_DETAILS | jq -r '.tx_hex' ) \
        && echo "RAW_P2TSH_SPEND_TX = $RAW_P2TSH_SPEND_TX" \
    && export SIG_HASH=$( echo $SPEND_DETAILS | jq -r '.sighash' ) \
        && echo "SIG_HASH = $SIG_HASH" \
    && export SIG_BYTES=$( echo $SPEND_DETAILS | jq -r '.sig_bytes' ) \
        && echo "SIG_BYTES = $SIG_BYTES"
-----

. Inspect the spending tx:
+
-----
$ b-cli decoderawtransaction $RAW_P2TSH_SPEND_TX
-----
+
Pay particular attention to the `vin.txinwitness` field.
Do the three elements (script input, script and control block) of the witness stack for this script path spend make sense ?
What do you observe as the first byte of the `control block` element ?

. Test standardness of the spending tx by sending to local mempool of p2tsh enabled Bitcoin Core:
+
-----
$ b-cli testmempoolaccept '["'''$RAW_P2TSH_SPEND_TX'''"]'
-----

. Submit tx:
+
-----
$ export P2TSH_SPENDING_TX_ID=$( b-cli sendrawtransaction $RAW_P2TSH_SPEND_TX ) \
    && echo $P2TSH_SPENDING_TX_ID
-----
+
NOTE:  Should return same tx id as was included in $RAW_P2TSH_SPEND_TX

== Mine P2TSH Spend TX

. View tx in mempool:
+
-----
$ b-cli getrawtransaction $P2TSH_SPENDING_TX_ID 1
-----
+
NOTE:  There will not yet be a field `blockhash` in the response.

. Mine 1 block:

.. regtest:
+
-----
$ b-cli -generate 1
-----

.. signet:
+
If on `signet` network, then execute the following:
+
-----
$ $BITCOIN_SOURCE_DIR/contrib/signet/miner --cli "bitcoin-cli -conf=$HOME/anduro-360/configs/bitcoin.conf.signet" generate \
    --address $P2TSH_ADDR \
    --grind-cmd "$BITCOIN_SOURCE_DIR/build/bin/bitcoin-util grind" \
    --min-nbits --set-block-time $(date +%s) \
    --poolid "MARA Pool"
-----

. Obtain `blockhash` field of mined tx:
+
-----
$ export BLOCK_HASH=$( b-cli getrawtransaction $P2TSH_SPENDING_TX_ID 1 | jq -r '.blockhash' ) \
    && echo $BLOCK_HASH
-----

. View tx in block:
+
-----
$ b-cli getblock $BLOCK_HASH | jq -r .tx
-----

== TO-DO

=== Import P2TSH address into wallet

NOTE:  currently fails with:   "message": "Cannot import descriptor without private keys to a wallet with private keys enabled"

-----
$ b-cli -rpcwallet=$W_NAME walletpassphrase $WPASS 120
$ echo $P2TSH_ADDR
$ export P2TSH_DESC=$( b-cli getdescriptorinfo "addr($P2TSH_ADDR)" | jq -r '.descriptor' ) \
    && echo $P2TSH_DESC

# Set as non-active address (because can't generate subsequent p2tsh addresses yet)
$ b-cli importdescriptors '[{
  "desc": "'''$P2TSH_DESC'''",
  "timestamp": "now",
  "active": false,
  "label": "p2tsh"
}]'
-----
